AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SubnetId:
    Type: String
  SecurityGroupIds:
    Type: String
  KeyName:
    Type: String
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t3.micro
      - t3.small
  ImageId:
    Type: String
    Default: ami-0166fe664262f664c

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref ImageId
      SubnetId: !Ref SubnetId
      SecurityGroupIds: 
        - !Ref SecurityGroupIds
      KeyName: !Ref KeyName
      Tags:
        - Key: Name
          Value: MyEC2Instance

