AWSTemplateFormatVersion: '2010-09-09'
Resources:
  VPC:  
    Type: AWS::EC2::VPC
    Properties:
     CidrBlock: 10.20.0.0/16
     EnableDnsSupport: true
     EnableDnsHostnames: true
     Tags:
     - Key: Name
       Value: MyVPC

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
     VpcId: !Ref VPC
     CidrBlock: 10.20.1.0/24
     MapPublicIpOnLaunch: true
     Tags: 
     - Key: Name
       Value: PublicSubnet

 

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
     
     Tags:
     - Key: Name
       Value: MyInternetGateway

  AttachInternetGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
     VpcId: !Ref VPC
     InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::PublicRouteTable
    Properties:
     VpcId: !Ref VPC
     Tags:
     - Key: Name
       Value: PublicRouteTable

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
     RouteTableId: !Ref PublicRouteTable
     DestinationCidrBlock: 0.0.0.0/0
     GatewayId: !Ref InternetGateway

  PublicSubnetRouteAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
     SubnetId: !Ref PublicSubnet
     RouteTableId: !Ref PublicRouteTable


   



