AWSTemplateFormatVersion: '2010-09-09'
Resources:
  VPC:  
    Type: AWS::EC2::VPC
    Properties:
     CidrBlock: 10.30.0.0/16
     EnableDnsSupport: true
     EnableDnsHostnames: true
     Tags:
     - Key: Name
       Value: MyVPC

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
     VpcId: !Ref VPC
     CidrBlock: 10.30.1.0/24
     AvailabilityZone: us-east-1a
     MapPublicIpOnLaunch: true
     Tags: 
     - Key: Name
       Value: PublicSubnet1

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
     VpcId: !Ref VPC
     CidrBlock: 10.30.2.0/24
     AvailabilityZone: us-east-1b
     MapPublicIpOnLaunch: true
     Tags: 
     - Key: Name
       Value: PublicSubnet2

  PublicSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
     VpcId: !Ref VPC
     CidrBlock: 10.30.3.0/24
     MapPublicIpOnLaunch: true
     Tags: 
     - Key: Name
       Value: PublicSubnet3          

 

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
     
     Tags:
     - Key: Name
       Value: MyInternetGateway

  AttachInternetGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
     VpcId: !Ref VPC
     InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
     VpcId: !Ref VPC
     Tags:
     - Key: Name
       Value: PublicRouteTable

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
     RouteTableId: !Ref PublicRouteTable
     DestinationCidrBlock: 0.0.0.0/0
     GatewayId: !Ref InternetGateway

  PublicSubnet1RouteAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
     SubnetId: !Ref PublicSubnet1
     RouteTableId: !Ref PublicRouteTable

  PublicSubnet2RouteAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
     SubnetId: !Ref PublicSubnet2
     RouteTableId: !Ref PublicRouteTable


  PublicSubnet3RouteAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
     SubnetId: !Ref PublicSubnet3
     RouteTableId: !Ref PublicRouteTable

   



